//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDEFExample
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string FullName { get; set; }
        public int ID { get; set; }

        public override string ToString()
        {
            return ("ID = " + this.ID + ", Full Name = " +
                        (this.FullName.Length > 20 ? this.FullName.Substring(0, 17) + "..." : this.FullName)
                        ); ;
        }
    }
}
